import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import ThemeToggler from "@/components/ThemeToggler";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider>
            <main className="min-h-screen grid place-items-center dark:bg-slate-900 dark:text-slate-300 p-4">
              {children}
            </main>
            <Toaster />
            <ThemeToggler />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
